<?php

function memcache_init() {
  if (strstr($_SERVER['PHP_SELF'], 'update.php') || strstr($_GET['q'], 'autocomplete')) {
    // update.php relies on standard error handler
  }
  else {
    drupal_add_js('misc/jquery.js');
    register_shutdown_function('memcache_shutdown');
  }
}


/**
 * See memcache_init() which registers this function as a shutdown function.
 * Displays memcache stats in the footer.
 */
function memcache_shutdown() {
  global $user, $memcache_statistics;

  $output = '';

  // Try not to break non html pages.
  if (function_exists('drupal_get_headers')) {
    $headers = drupal_get_headers();
    if(strstr($headers, 'xml') || strstr($headers, 'javascript') || strstr($headers, 'plain')) {
      return;
    }
  }

  if ($user->uid == 1) {
    $stats = array();
    foreach ($memcache_statistics as $stat => $val) {
      $stats[] = "<strong>$stat:</strong> $val";
    }
    if (!empty($stats)) {
      $output = theme('item_list', $stats);
      // this makes sure all of the HTML is within the <body> even though this <script> is outside it
      print '<script type="text/javascript">
        $(document).ready(function() {
          $("body").append("'. str_replace(array("\r", "\n", "<", ">", "&"),
                                           array('\r', '\n', '\x3c', '\x3e', '\x26'),
                                           addslashes($output)) .'");
        });
      </script>';
    }
  }
}
