<?php

/**
 * For the collection of memcache stats. This small .js file makes sure that the
 * HTML displaying the stats is inside of the <body> part of the HTML
 * document.
 */
function memcache_admin_init() {
  global $user;
  if (($user->uid == 0) || strstr($_SERVER['PHP_SELF'], 'update.php') || (isset($_GET['q']) && (in_array($_GET['q'], array('upload/js', 'admin/content/node-settings/rebuild')) || substr($_GET['q'], 0, strlen('system/files')) == 'system/files' || substr($_GET['q'], 0, strlen('batch')) == 'batch' || strstr($_GET['q'], 'autocomplete')))) {
    // update.php relies on standard error handler
  }
  else {
    if ($user->uid) {
      drupal_add_js(drupal_get_path('module', 'memcache_admin'). '/memcache.js');
    }
    register_shutdown_function('memcache_admin_shutdown');
  }
}

/**
 * Implementation of hook_perm().
 */
function memcache_admin_perm() {
  return array('access memcache statistics', 'access slab cachedump');
}

/**
 * Implementation of hook_menu().
 */
function memcache_admin_menu() {
  $items['admin/settings/memcache'] = array(
    'title' => 'Memcache',
    'description' => 'Show or hide memcache statistics at the bottom of each page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('memcache_admin_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/reports/memcache'] = array(
    'title' => 'Memcache statistics',
    'description' => "View statistics for all configured memcache servers.",
    'page callback' => 'memcache_admin_stats',
    'access arguments' => array('access memcache statistics'),
    'weight' => 1,
  );
  $memcache_servers = variable_get('memcache_servers', array('127.0.0.1:11211' => 'default'));
  $clusters = array();
  foreach($memcache_servers as $server => $cluster) {
    $clusters[$cluster]['servers'][] = $server;
    $clusters[$cluster]['bin'] = _memcache_admin_get_bin_for_cluster($cluster);
  }

  $count = 0;
  foreach ($clusters as $cluster => $cluster_info) {
    if ($cluster_info['bin']) {
      if (empty($current_cluster)) {
        $current_cluster = arg(3);
        if (empty($current_cluster)) {
          $current_cluster = $cluster;
        }
      }

      $items['admin/reports/memcache/'. $cluster] = array(
        'title' => $cluster,
        'type' =>  $count == 0 ? MENU_DEFAULT_LOCAL_TASK : MENU_LOCAL_TASK,
        'page callback' => 'memcache_admin_stats',
        'page arguments' => array($cluster),
        'access arguments' => array('access memcache statistics'),
        'weight' => $count++,
      );
      foreach ($cluster_info['servers'] as $server) {
        $items["admin/reports/memcache/$cluster/$server"] = array(
          'title' => check_plain($server),
          'type' =>  MENU_CALLBACK,
          'page callback' => 'memcache_admin_stats_raw',
          'page arguments' => array($cluster, $server),
          'access arguments' => array('access memcache statistics'),
        );
        foreach (memcache_admin_stats_types($cluster) as $type) {
          $items["admin/reports/memcache/$cluster/$server/$type"] = array(
            'type' => MENU_CALLBACK,
            'page callback' => 'memcache_admin_stats_raw',
            'page arguments' => array($cluster, $server, $type),
            'title' => $type,
            'access arguments' => array('access memcache statistics'),
          );
        }
      }
    }
  }

  return $items;
}

/**
 * Settings form.
 */
function memcache_admin_admin_settings() {
  $form['show_memcache_statistics'] = array('#type' => 'checkbox',
    '#title' => t('Show memcache statistics at the bottom of each page'),
    '#default_value' => variable_get('show_memcache_statistics', 1),
    '#description' => t("These statistics will be visible to users with the 'access memcache statistics' permission."),
  );
  return system_settings_form($form);
}

function _memcache_admin_default_bin($bin) {
  if ($bin == 'default') {
    return 'cache';
  }
  return $bin;
}

function _memcache_admin_stats_connections($current, $total) {
  return t('!current open of !total total', array('!current' => number_format($current), '!total' => number_format($total)));
}

/**
 * Statistics report: calculate # of set cmds and total cmds.
 */
function _memcache_admin_stats_sets($cmd_set, $cmd_get) {
  if (($cmd_set + $cmd_get) == 0) {
    $sets = 0;
  }
  else {
    $sets = $cmd_set / ($cmd_set + $cmd_get) * 100;
  }
  return t('!set sets (!sets%) of !total commands', array('!sets' => number_format($sets, 2), '!set' => number_format($cmd_set), '!total' => number_format($cmd_set + $cmd_get)));
}

/**
 * Statistics report: calculate # of get cmds, broken down by hits and misses.
 */
function _memcache_admin_stats_gets($cmd_set, $cmd_get, $get_hits, $get_misses) {
  if (($cmd_set + $cmd_get) == 0) {
    $gets = 0;
  }
  else {
    $gets = $cmd_get / ($cmd_set + $cmd_get) * 100;
  }
  return t('!total gets (!gets%), !hit hits (!percent_hit%) !miss misses (!percent_miss%)', array('!gets' => number_format($gets, 2), '!hit' => number_format($get_hits), '!percent_hit' => ($cmd_get > 0 ? number_format($get_hits / $cmd_get * 100, 2) : '0.00'), '!miss' => number_format($get_misses), '!percent_miss' => ($cmd_get > 0 ? number_format($get_misses / $cmd_get * 100, 2) : '0.00'), '!total' => number_format($cmd_get)));
}

/**
 * Statistics report: calculate # of increments and decrements.
 */
function _memcache_admin_stats_counters($incr_hits, $incr_misses, $dec_hits, $decr_misses) {
  return t('!incr increments, !decr decrements', array('!incr' => number_format($incr_hits + $incr_misses), '!decr' => number_format($decr_hits + $decr_misses)));
}

/**
 * Statistics report: calculate bytes transferred.
 */
function _memcache_admin_stats_transfer($bytes_read, $bytes_written) {
  if ($bytes_written == 0) {
    $written = 0;
  }
  else {
    $written = $bytes_read / $bytes_written * 100;
  }
  return t('!to:!from (!written% to cache)', array('!to' => format_size((int)$bytes_read), '!from' => format_size((int)$bytes_written), '!written' => number_format($written, 2)));
}

/**
 * Statistics report: calculate per-connection averages.
 */
function _memcache_admin_stats_average($cmd_get, $total_connections, $cmd_set, $bytes_read, $bytes_written) {
  if ($total_connections == 0) {
    $get = 0;
    $set = 0;
    $read = 0;
    $write = 0;
  }
  else {
    $get = $cmd_get / $total_connections;
    $set = $cmd_set / $total_connections;
    $read = $bytes_written / $total_connections;
    $write = $bytes_read / $total_connections;
  }
  return t('!read in !get gets, !write in !set sets', array('!get' => number_format($get, 2), '!set' => number_format($set, 2), '!read' => format_size(number_format($read, 2)), '!write' => format_size(number_format($write, 2))));
}

/**
 * Statistics report: calculate available memory.
 */
function _memcache_admin_stats_memory($limit_maxbytes, $bytes) {
  if ($limit_maxbytes == 0) {
    $percent = 0;
  }
  else {
    $percent = 100 - $bytes / $limit_maxbytes * 100;
  }
  return t('!available (!percent%) of !total', array('!available' => format_size($limit_maxbytes - $bytes), '!percent' => number_format($percent, 2), '!total' => format_size($limit_maxbytes)));
}

/**
 * Helper function, reverse map the memcache_bins variable.
 */
function memcache_admin_bin_mapping($bin = 'cache') {
  $bins = array_flip(variable_get('memcache_bins', array('cache' => 'default')));
  if (isset($bins[$bin])) {
    return $bins[$bin];
  }
  else {
    // The default bin is 'cache'.
    return _memcache_admin_default_bin($bin);
  }
}

/**
 * Memcahe Stats page
 *
 * @return string
 */
function memcache_admin_stats($bin = 'cache') {
  $bin = memcache_admin_bin_mapping($bin);

  $stats = dmemcache_stats($bin, 'default', TRUE);

  $memcache_servers = variable_get('memcache_servers', array('127.0.0.1:11211' => 'default'));

  if (is_array($stats[$bin]) && count($stats[$bin])) {
    $stats = $stats[$bin];

    $mc = dmemcache_object($bin);
    if ($mc instanceof Memcached) {
      $version = t('Memcached v!version', array('!version' => phpversion('Memcached')));
    }
    elseif ($mc instanceof Memcache) {
      $version = t('Memcache v!version', array('!version' => phpversion('Memcache')));
    }
    else {
      $version = t('Unknown');
      drupal_set_message(t('Failed to detect the memcache PECL extension.'), 'error');
    }

    // Building per-server stats for the current memcache bin.
    $servers = array();
    foreach ($memcache_servers as $server => $b) {
      $b = memcache_admin_bin_mapping($b);
      if ($b == $bin) {
        $servers[] = $server;

        if (empty($stats[$server]['uptime'])) {
          drupal_set_message(t('Failed to connect to server at %server.', array('%server' => $server)), 'error');
        }
        $data['server_overview'][$server] = t('v!version running !uptime', array('!version' => check_plain($stats[$server]['version']), '!uptime' => format_interval($stats[$server]['uptime'])));
        $data['server_pecl'][$server] = t('n/a');
        $data['server_time'][$server] = format_date($stats[$server]['time']);
        $data['server_connections'][$server] = _memcache_admin_stats_connections($stats[$server]['curr_connections'], $stats[$server]['total_connections']);
        $data['cache_sets'][$server] = _memcache_admin_stats_sets($stats[$server]['cmd_set'], $stats[$server]['cmd_get']);
        $data['cache_gets'][$server] = _memcache_admin_stats_gets($stats[$server]['cmd_set'], $stats[$server]['cmd_get'], $stats[$server]['get_hits'], $stats[$server]['get_misses']);
        $data['cache_counters'][$server] = _memcache_admin_stats_counters($stats[$server]['incr_hits'], $stats[$server]['incr_misses'], $stats[$server]['decr_hits'], $stats[$server]['decr_misses']);
        $data['cache_transfer'][$server] = _memcache_admin_stats_transfer($stats[$server]['bytes_read'], $stats[$server]['bytes_written']);
        $data['cache_average'][$server] = _memcache_admin_stats_average($stats[$server]['cmd_get'], $stats[$server]['total_connections'], $stats[$server]['cmd_set'], $stats[$server]['bytes_read'], $stats[$server]['bytes_written']);
        $data['memory_available'][$server] = _memcache_admin_stats_memory($stats[$server]['limit_maxbytes'], $stats[$server]['bytes']);
        $data['memory_evictions'][$server] = number_format($stats[$server]['evictions']);
      }
    }
    // Building a report as a custom formatted array of arrays that gets
    // properly displayed by theme_memcache_admin_stats_table.
    $report = array(
      'Server overview' => array(
        array_merge(
          array('header' => t('Uptime')),
          array('total' => t('n/a')),
          $data['server_overview']),
        array_merge(
          array('header' => t('PECL extension')),
          array('total' => $version),
          $data['server_pecl']),
        array_merge(
          array('header' => t('Time')),
          array('total' => t('n/a')),
          $data['server_time']),
        array_merge(
          array('header' => t('Connections')),
          array('total' => _memcache_admin_stats_connections($stats['total']['curr_connections'], $stats['total']['total_connections'])),
          $data['server_connections']),
      ),
      'Cache statistics' => array(
        array_merge(
          array('header' => t('Sets')),
          array('total' => _memcache_admin_stats_sets($stats['total']['cmd_set'], $stats['total']['cmd_get'])),
          $data['cache_sets']),
        array_merge(
          array('header' => t('Gets')),
          array('total' => _memcache_admin_stats_gets($stats['total']['cmd_set'], $stats['total']['cmd_get'], $stats['total']['get_hits'], $stats['total']['get_misses'])),
          $data['cache_gets']),
        array_merge(
          array('header' => t('Counters')),
          array('total' => _memcache_admin_stats_counters($stats['total']['incr_hits'], $stats['total']['incr_misses'], $stats['total']['decr_hits'], $stats['total']['decr_misses'])),
          $data['cache_counters']),
        array_merge(
          array('header' => t('Transferred')),
          array('total' => _memcache_admin_stats_transfer($stats['total']['bytes_read'], $stats['total']['bytes_written'])),
          $data['cache_transfer']),
        array_merge(
          array('header' => t('Per-connection average')),
          array('total' => _memcache_admin_stats_average($stats['total']['cmd_get'], $stats['total']['total_connections'], $stats['total']['cmd_set'], $stats['total']['bytes_read'], $stats['total']['bytes_written'])),
          $data['cache_average']),
      ),
      'Memory overview' => array(
        array_merge(
          array('header' => t('Available memory')),
          array('total' => _memcache_admin_stats_memory($stats['total']['limit_maxbytes'], $stats['total']['bytes'])),
          $data['memory_available']),
        array_merge(
          array('header' => t('Evictions')),
          array('total' => $stats['total']['evictions']),
          $data['memory_evictions']),
      ),
    );
    $output .= theme('memcache_admin_stats_table', $bin, $servers, $report);
  }
  else {
    $output = '';
    drupal_set_message(t('There are no statistics being reported for this bin.'), 'error');
  }

  return $output;
}

function memcache_admin_stats_raw($bin, $server, $type = 'default') {
  $cluster = memcache_admin_bin_mapping($bin);
  $slab = (int)arg(7);
  if (arg(6) == 'cachedump' && !empty($slab) && user_access('access slab cachedump')) {
    $stats = dmemcache_stats($cluster, arg(7), FALSE);
  }
  else {
    $stats = dmemcache_stats($cluster, $type, FALSE);
  }
  $breadcrumbs = array(l(t('Home'), NULL), l(t('Administer'), 'admin'), l(t('Reports'), 'admin/reports'), l(t('Memcache'), 'admin/reports/memcache'), l(t($bin), "admin/reports/memcache/$bin"));
  if ($type == 'slabs' && arg(6) == 'cachedump' && user_access('access slab cachedump')) {
    $breadcrumbs[] = l($server, "admin/reports/memcache/$bin/$server");
    $breadcrumbs[] = l('slabs', "admin/reports/memcache/$bin/$server/$type");
  }
  drupal_set_breadcrumb($breadcrumbs);
  if (is_array($stats[$cluster][$server]) && count($stats[$cluster][$server])) {
    $output .= theme('memcache_admin_stats_raw_table', $cluster, $server, $stats[$cluster][$server], $type);
  }
  elseif ($type == 'slabs' && is_array($stats[$cluster]) && count($stats[$cluster])) {
    $output .= theme('memcache_admin_stats_raw_table', $cluster, $server, $stats[$cluster], $type);
  }
  else {
    $output = '';
    drupal_set_message(t('No !type statistics for this bin.', array('!type' => $type)));
  }
  return $output;
}

/**
 * Implementation of hook_theme().
 */
function memcache_admin_theme() {
  return array(
    'memcache_admin_stats_table' => array(
      'arguments' => array('bin' => NULL, 'servers' => NULL, 'report' => NULL),
    ),
    'memcache_admin_stats_raw_table' => array(
      'arguments' => array('bin' => NULL, 'server' => NULL, 'stats' => NULL, 'type' => NULL),
    )
  );
}

/**
 * Theme function for rendering the output from memcache_admin_stats
 *
 * @param string $server - Server name:port for caption for the table
 * @param array $stats - array of key/value string pairs for the table results
 * @return string
 */
function theme_memcache_admin_stats_table($bin, $servers, $stats) {
  $output = '';
  $links = array();
  $memcache_bins = variable_get('memcache_bins', array('cache' => 'default'));
  foreach ($servers as $server) {
    $link_bin = $memcache_bins[$bin];
    $links[] = l($server, check_plain("admin/reports/memcache/$link_bin/$server"));
  }
  $headers = array_merge(array('', t('Totals')), $links);
  foreach ($stats as $table => $data) {
    $rows = array();
    foreach ($data as $row) {
      if (is_array($row[2])) {
        $row[2] = implode(', ', $row[2]);
      }
      else {
        $row[2] = '';
      }
      $rows[] = $row;
    }
    $output .= theme('table', $headers, $rows);
  }
  return $output;
}

function memcache_admin_stats_types($bin) {
  if ($mc = dmemcache_object($bin)) {
    if ($mc instanceof Memcache) {
      // TODO: Determine which versions of the PECL memcache extension have
      // these other stats types: 'malloc', 'maps', optionally detect this
      // version and expose them.  These stats are "subject to change without
      // warning" unfortunately.
      return array('default', 'slabs', 'items', 'sizes');
    }
    else {
      // The Memcached PECL extension only offers the default statistics.
      return array('default');
    }
  }
}

function theme_memcache_admin_stats_raw_table($cluster, $server, $stats, $current_type = 'default') {
  $memcache_bins = variable_get('memcache_bins', array());
  $bin = isset($memcache_bins[$cluster]) ? $memcache_bins[$cluster] : 'default';
  // Provide navigation for the various memcache stats types
  if (count(memcache_admin_stats_types($bin)) > 1) {
    foreach (memcache_admin_stats_types($bin) as $type) {
      if ($current_type == $type) {
        $links[] = '<strong>' . l(t($type), "admin/reports/memcache/$bin/$server/". ($type == 'default' ? '' : $type)) .'</strong>';
      }
      else {
        $links[] = l(t($type), "admin/reports/memcache/$bin/$server/". ($type == 'default' ? '' : $type));
      }
    }
  }
  $output = !empty($links) ? implode($links, ' | ') : '';

  $headers = array(t('Property'), t('Value'));
  $rows = array();
  // Items are returned as an array within an array within an array.  We step
  // in one level to properly display the contained statistics.
  if ($current_type == 'items' && isset($stats['items'])) {
    $stats = $stats['items'];
  }
  foreach ($stats as $key => $value) {
    // Add navigation for getting a cachedump of individual slabs
    if (($current_type == 'slabs' || $current_type == 'items') && is_int($key) && user_access('access slab cachedump')) {
      $key = l($key, "admin/reports/memcache/$bin/$server/slabs/cachedump/$key");
    }
    if (is_array($value)) {
      $rs = array();
      foreach ($value as $k => $v) {
        // Format timestamp when viewing cachedump of individual slabs.
        if ($current_type == 'slabs' && user_access('access slab cachedump') && arg(6) == 'cachedump' && $k == 0) {
          $k = t('Size');
          $v = format_size($v);
        }
        else if ($current_type == 'slabs' && user_access('access slab cachedump') && arg(6) == 'cachedump' && $k == 1) {
          $k = t('Expire');
          $full_stats = dmemcache_stats($cluster, 'default');
          $infinite = $full_stats[$cluster][$server]['time'] - $full_stats[$cluster][$server]['uptime'];
          if ($v == $infinite) {
            $v = t('infinite');
          }
          else {
            $v = t('in @time', array('@time' => format_interval($v - time())));
          }
        }
        $rs[] = array(check_plain($k), check_plain($v));
      }
      $rows[] = array($key, theme('table', array(), $rs));
    }
    else {
      $rows[] = array(check_plain($key), check_plain($value));
    }
  }
  $output .= theme('table', $headers, $rows);
  return $output;
}

/**
 * Retrieve the cluster for any given bin
 *
 * @param string $cluster - Cluster ID
 * @return string
 */
function _memcache_admin_get_bin_for_cluster($cluster) {
  static $cluster_map = array();

  if (!isset($cluster_map[$cluster])) {
    $memcache_bins = variable_get('memcache_bins', array());
    if ($mapping = array_search($cluster, $memcache_bins)) {
      $cluster_map[$cluster] = $mapping;
    }
    else {
      $cluster_map[$cluster] = 'default';
    }
  }

  return $cluster_map[$cluster];
}

/**
 * See memcache_admin_init() which registers this function as a shutdown function.
 * Displays memcache stats in the footer.
 */
function memcache_admin_shutdown() {
  global $_memcache_statistics;

  // Don't call theme() during shutdown if the registry has been rebuilt (such
  // as when enabling/disabling modules on admin/build/modules) as things break.
  // Instead, simply exit without displaying admin statistics for this page
  // load.  See http://drupal.org/node/616282 for discussion.
  if (!function_exists('theme_get_registry') || !theme_get_registry()) {
    return;
  }

  // Try not to break non-HTML pages.
  if (function_exists('drupal_get_headers')) {
    $headers = drupal_get_headers();
    if(strstr($headers, 'xml') || strstr($headers, 'javascript') || strstr($headers, 'plain')) {
      return;
    }
  }

  if (variable_get('show_memcache_statistics', TRUE) && function_exists('user_access') && user_access('access memcache statistics')) {
    if (!empty($_memcache_statistics)) {
      foreach ($_memcache_statistics as $row => $stats) {
        $_memcache_statistics[$row][1] = check_plain($stats[1]);
        $_memcache_statistics[$row][2] = check_plain($stats[2]);
      }

      $headers = array(t('Operation'), t('Bin'), t('Key'), t('Hit'));
      $output = theme('table', $headers, $_memcache_statistics);

      // this makes sure all of the HTML is within the <body> even though this <script> is outside it
      print '<div id="memcache-devel"><h2>'. t('Memcache statistics'). '</h2>'. $output. '</div>';
    }
  }
}
